#============================== Configuration Apache TomCat
server:
  port: 8082
#============================== Configuration Logging
logging:
  file: /tmp/log/library-service.log
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.data: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO
    com.trl.libraryservice: DEBUG

spring:
  profiles.active: dev
  application:
    name: library-service

  #============================== Configuration Eureka Client
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

  #============================== Configuration PostgreSQL
  datasource:
    username: developer
    password: Nqa2GrwJ5dqu
    url: jdbc:postgresql://ec2-15-188-76-238.eu-west-3.compute.amazonaws.com/library_service
    driver-class-name: org.postgresql.Driver

  #============================== Configuration JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  #    database-platform: org.hibernate.dialect.H2Dialect

#  #============================== Configuration H2
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#
#  datasource:
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:library
